### ISSUE TITLE
Spotify crashes after awhile.

### ISSUE THREAD

**Issue by jessyreynosa3** [bermudalocket/MeltedCrayons#1]
After a while of playing sometimes the same song or skipping to the next track, the music will abruptly cut off and the Spotify app will become none responsive. After force closing it once or twice the app can relaunch without none of the tweaks loaded. 

These are what I have installed
![4B54C97B-5CBE-4493-8B88-532D44AC25A4](https://user-images.githubusercontent.com/62078936/76464518-e88fe500-63bb-11ea-9719-882874107a8a.png)

 - Device: iPhone 11 Pro Max
 - OS: iOS13.3.

**Comment by mueller-alex** [comment]
Also getting this, it also occasionally freezes my phone completely to the point where I'm only able to swipe down the notification center and control center, but I'm unable to enter multitasking. I have to respring for it to respond again.

**Comment by zabinga73** [comment]
Similar Issue except my app freezes and needs to be restarted twice for the tweak to show again

**Comment by hoaphm** [comment]
If you guys have the tweak Sposify installed, disable it may fix Spotify crashing

**Comment by dev-luisraul** [comment]
I'm using both Sposify and Groovify in conjunction with this tweak, but getting the same issue. Hopefully this gets resolved soon!

**Comment by slsgill** [comment]
Same thing happens for me, it crashes after a while. But I noticed it’s when I press the shuffle button. I have no Spotify tweaks other than this I’m on iPhone 8plus 13.3.1

**Comment by bermudalocket** [comment]
Yeah I don't think Sposify is the issue. This problem has been difficult to track down but hopefully v1.0.1 fixes it.

**Comment by bermudalocket** [comment]
Hopefully fixed in 1.0.2.
