### ISSUE TITLE
Identify and fix possible memory leak

### ISSUE THREAD

**Issue by bermudalocket** [bermudalocket/MeltedCrayons#10]
_Originally posted by @ALMR-Designs in https://github.com/bermudalocket/MeltedCrayons/issues/1#issuecomment-597935027_

Also getting this, it also occasionally freezes my phone completely to the point where I'm only able to swipe down the notification center and control center, but I'm unable to enter multitasking. I have to respring for it to respond again.

**Comment by zabinga73** [comment]
could this be what causes less dramatic freezes as well?
less dramatic meaning i can exit the app and close it after it froze
