### ISSUE TITLE
White bug.

### ISSUE THREAD

**Issue by KikeMartinG93** [bermudalocket/MeltedCrayons#13]
**Describe the bug**
When skipping songs, or going trough the views sometimes you get a white or black bar going from the bottom of the artwork all the way to the bottom of the screen

11ProMax 13.3
Video: https://www.icloud.com/sharedalbum/#B0OGWZuqDqNFab7

**Comment by bermudalocket** [comment]
Unfortunately I'm not sure there's anything I can do about this.

**Comment by KikeMartinG93** [comment]
> Unfortunately I'm not sure there's anything I can do about this.

What do u mean. Mind to elaborate?

**Comment by bermudalocket** [comment]
> What do u mean. Mind to elaborate?

For some reason Apple resets the background color of the controls view (which is separate from the background view and album art view) every time `layoutSubviews` is called -- a lot. The code I inserted to change the white color to a clear color is already being called as early as I can possibly call it. I can put some time into looking for an earlier hook but I admit it's not exactly high priority right now.

**Comment by bermudalocket** [comment]
Moved the code around so the white background change is caught a _tiny_ bit earlier. It's not perfect but it's better than it was. Sometimes it's caught so quickly the white never even appears.
