### ISSUE TITLE
Music App Crashing/ Lag in changing background colors

### ISSUE THREAD

**Issue by Captainbootyclap** [bermudalocket/MeltedCrayons#15]
Description: 
When using the music app it will randomly freeze while opening the mini player and crash. Also when skipping songs there is a slight lag in the background changing artwork or at least no animation

To Reproduce:
1) Open Music App
2)Skip through tracks 

Expected behavior:
Having the music app not crash when opening the miniplayer. Also for there to not be a lag when skipping tracks or at least have there be an animation

 - Device: iPhone 11 Pro Max
 - OS: iOS 13.3

**Comment by bermudalocket** [comment]
Fixed in 1.0.2.
