### ISSUE TITLE
Glitchy in music app when minimizing/opening the now playing card

### ISSUE THREAD

**Issue by GoutiB** [bermudalocket/MeltedCrayons#16]
[Video illustrating issue](https://filebin.net/gb3i3xvi1mh6yl4c) 

The music app is glitchy (though perfectly usable) also spotify has random freezes. I have no tweaks on spotify and music app. Used to have colorflow5 but removed it before installing this tweak.

Device: 11 pro
Version :13.3

**Comment by bermudalocket** [comment]
Smoothed the appear/disappear animation in 1.0.2.
