### ISSUE TITLE
Spotify crashes

### ISSUE THREAD

**Issue by shatteredice67** [bermudalocket/MeltedCrayons#17]
**Describe the bug**
Spotify occasionally crashes when changing songs
**To Reproduce**
1. Open Spotify
2. Change songs in playlist with different album art
3.spotify crashes
**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 8+
 - OS: iOS13.3

**Additional context**

**Comment by bermudalocket** [comment]
Duplicate of #1
