### ISSUE TITLE
Preference Bundle

### ISSUE THREAD

**Issue by j626w** [bermudalocket/MeltedCrayons#18]
**Is your feature request related to a problem? Please describe.**
Settings others described on first launch weren’t shown, only the tweak name.

**Describe the solution you'd like**
Preference bundle in settings or better integration into spotify/music app settings.

**Describe alternatives you've considered**
No real alternatives. Can’t change anything about the tweak currently and am stuck without an animated background :/

**Comment by bermudalocket** [comment]
> Settings others described on first launch weren’t shown

I'm not sure where you saw that settings were being offered. I never mentioned settings in any of my preview posts. However, I do like the idea of being able to tweak the effect to your own liking so I will add support for this.

**Comment by j626w** [comment]
I got the impression I missed some setting, since I never got any animated view. Just assumed that there was a toggle or something on that startup screen. Glad it’s an addition though, thanks for the great support so far.

**Comment by bermudalocket** [comment]
Preference bundle added in 1.0.2.
