### ISSUE TITLE
No animated background

### ISSUE THREAD

**Issue by j626w** [bermudalocket/MeltedCrayons#19]
**Describe the bug**
Background is never animated, only static.

**To Reproduce**
1. Install tweak
2. Open Spotify
3. ???
4. Profit

**Expected behavior**
Animated background or option to see them

**Smartphone:**
 - Device: X global 256
 - OS: 13.3.1

**Additional context**
Attempted to fix by disabling all other tweaks for potential conflicts, even reinstalling the tweak. No luck.

**Comment by bermudalocket** [comment]
Should be fixed in 1.0.2.
