### ISSUE TITLE
Dynamic color vibrancy

### ISSUE THREAD

**Issue by andremoi123** [bermudalocket/MeltedCrayons#2]
**Is your feature request related to a problem? Not really.
**Describe the solution you'd like**
A update in the future and a more tighter color grasp in the future plz.

**Describe alternatives you've considered**

Dynamic color vibrancy for dark mode like apple’s implementation. On pause the visualizer is moving while darker but on play its vibrancy brightens up to the Vibrancy of the light mode visualizer.

**Additional context**
I have a vid/gif to explain...
https://share.icloud.com/photos/0X8j6nuG5VErc6AgekAV9J5cg

**Comment by bermudalocket** [comment]
Oh that's a fun one. Thanks for reporting, I'll look into it.

**Comment by bermudalocket** [comment]
Should be fixed in 1.0.2.
