### ISSUE TITLE
Not installing correctly 

### ISSUE THREAD

**Issue by cheesecake9** [bermudalocket/MeltedCrayons#22]
I’ve tried installing the tweak through zebra and cydia and it doesn’t seem to install correctly. 

The tweak doesn’t show up in settings at all or anything. And it installs to the root directory / 
![51351761-656E-442A-9665-07BBBBBE9889](https://user-images.githubusercontent.com/62110637/76570706-4c81de80-648c-11ea-9a61-ea9d46ea7043.png)
![EB4C38C8-7098-4236-AA92-9BAB17B30A05](https://user-images.githubusercontent.com/62110637/76570712-4f7ccf00-648c-11ea-8390-673e88eadde2.png)
![EBD3A03A-D125-4332-8055-D0EB32FD64D1](https://user-images.githubusercontent.com/62110637/76570714-50156580-648c-11ea-9516-6d83c3256b3d.png)

**Comment by bermudalocket** [comment]
This is not an issue with the tweak. I encourage you to try another package manager.

**Comment by cheesecake9** [comment]
Well, I’ve tried there different package managers, cydia, Zebra , and installer. They all have the same outcome. So I was wondering if you could help me further trouble shoot or just provide a refund. Thanks

**Comment by bermudalocket** [comment]
I'm confused: does the tweak work or not? There are currently no settings to configure so it not showing up in Settings is normal behavior. I'm not sure why the extra bundle installed to your root directory (it's definitely not set up that way in the Makefile), but that shouldn't affect the functionality of the tweak itself, only the welcome screen. I understand not wanting a bundle in your root directory, hence suggesting trying another package manager. You can most likely (re)move the bundle at your whim.

**Comment by cheesecake9** [comment]
I know there’s no setting preferences but even then the tweak doesn’t work. Neither in Spotify or Apple Music. And I’ve already tried removing the bundle from root but it doesn’t make a difference.
