### ISSUE TITLE
Apple Music Crashing After Respring

### ISSUE THREAD

**Issue by mrdrummerboy97** [bermudalocket/MeltedCrayons#27]
**Describe the bug**
Right after I respring my device, if I go to open Apple Music, it will immediately crash and I don’t get the colors or the tweak itself to work.

**To Reproduce**
1. Go to 'Home Screen’
2. Click on 'Apple Music'
3. See error

**Expected behavior**
To respring my device and the tweak preform normally upon pulling up Apple Music and playing any song or playlist without immediately crashing.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 13.3

**Additional context**
I did just recently install the tweak DarkPapers/WallpaperLoader, as well as AutoUnlockX. Not sure if any of these tweaks cause issues with MeltedCrayons but just thought I’d include.

**Comment by bermudalocket** [comment]
Can you submit a crash log from Cr4shed or Crash Reporter?

**Comment by mrdrummerboy97** [comment]
I solved the issue. It was unrelated to the tweak specifically!
