### ISSUE TITLE
Background not changing with song.

### ISSUE THREAD

**Issue by zabinga73** [bermudalocket/MeltedCrayons#29]
**Describe the bug**

**To Reproduce**
1. Go to Spotify
2. Play a song
3. Skip song or wait for it to finish
4. See how the background doesnt change when the next one starts

**Expected behavior**
The background to change with the song.

**Screenshots**
![2E3090D4-BAB0-4FCE-B86B-A8E2ED04854C](https://user-images.githubusercontent.com/62087923/76692645-7bc45700-6616-11ea-9502-b29d77e6077b.png)
Losing Something’s background

![89880887-16A5-4C74-8816-779980AAAC40](https://user-images.githubusercontent.com/62087923/76692651-9c8cac80-6616-11ea-9e8b-d31a24ad0095.png)
Losing Something’s background although Just is playing.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneXR
 - OS: iOS 13.3 unc0ver 4.3.1

**Additional context**
the background is still animated, both on the correct and incorrect songs.

**Comment by mrdrummerboy97** [comment]
I am also having the same issue. I just upgraded to 1.0.2b54-1+debug and was able to replicate the issue.
Device: iPhone XS
OS: iOS 13.3 unc0ver v4.3.1 Attached is the video of it happening on my device upon first opening Apple Music. (https://share.icloud.com/photos/0Nk4t2zIjoojhQv1MujyCxeDw)

**Comment by bermudalocket** [comment]
Just pushed 1.0.2b71 to Twickd. Let me know if this persists.

**Comment by zabinga73** [comment]
The issue is solved, thank you
