### ISSUE TITLE
An animation when opening/closing the player

### ISSUE THREAD

**Issue by tychoregter** [bermudalocket/MeltedCrayons#4]
I think the animation when you open or close the player is a little choppy, it hops right from your look to the regular colors, I think adding an animation to this would fix it, a fade in/out would be perfect in my opinion, I’m not sure if it’s even possible but if it is it would be an amazing addition I think.

**Comment by tychoregter** [comment]
I’ll add yet another thing to this: it would be great if a fade could also be added when skipping to the next (or previous) song

**Comment by samoht9277** [comment]
THIS

**Comment by bermudalocket** [comment]
Added a transition when opening/closing the player. Cross-fading will be added in the future. See #24
